# Generated by Django 3.1.1 on 2020-09-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='not_an_image', upload_to='static/known_faces/Sentdex'),
            preserve_default=False,
        ),
    ]
