# Generated by Django 3.1.1 on 2020-09-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0003_auto_20200922_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='not an image', upload_to='static/known_faces/Sentdex'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
