# Generated by Django 3.1.1 on 2020-09-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0004_auto_20200922_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
